### ISSUE TITLE
Modules not being found when running setup.py

### ISSUE THREAD

**Issue by FederalX** [ClarityCafe/Ivy#10]
Following the instructions outlined within the 'Setting up Ivy' wiki page, downloading the dependencies and placing Fern's data within the resources folder, running setup.py results in a traceback error:

`Traceback (most recent call last):
  File "F:\Ivy\setup.py", line 1, in <module>
    from ChatLearner.chatbot.bottrainer import BotTrainer
ModuleNotFoundError: No module named 'ChatLearner.chatbot'`

Seeing this, I decided to dig within the ChatLearner folder, and nothing was there. Do I have to download files that weren't outlined within the instructions elsewhere?

**Comment by sr229** [comment]
ChatLearner is a Git submodule. you can grab this with `git submodule update --init`

**Comment by sr229** [comment]
Documentation updated. Thanks for reporting
